function(configure_network_proxy http_proxy https_proxy)
    if(NOT http_proxy)
        set(CUSTOM_HTTP_PROXY "" CACHE STRING "HTTP proxy, e.g., http://127.0.0.1:7890")
    endif()
    if(NOT https_proxy)
        set(CUSTOM_HTTPS_PROXY "" CACHE STRING "HTTPS proxy, e.g., http://127.0.0.1:7890")
    endif()

    if(http_proxy)
        message(STATUS "Setting HTTP proxy: ${http_proxy}")
        set(ENV{http_proxy} "${http_proxy}")
    endif()
    if(https_proxy)
        message(STATUS "Setting HTTPS proxy: ${https_proxy}")
        set(ENV{https_proxy} "${https_proxy}")
    endif()
endfunction()