function(configure_ninja_response_files)
    if(CMAKE_GENERATOR MATCHES "Ninja" AND MSVC)
        set(CMAKE_NINJA_FORCE_RESPONSE_FILE ON CACHE BOOL "Use response file")
        set(CMAKE_C_USE_RESPONSE_FILE_FOR_OBJECTS ON CACHE BOOL "Use response file")
        set(CMAKE_CXX_USE_RESPONSE_FILE_FOR_OBJECTS ON CACHE BOOL "Use response file")
        set(CMAKE_C_USE_RESPONSE_FILE_FOR_INCLUDES ON CACHE BOOL "Use response file")
        set(CMAKE_CXX_USE_RESPONSE_FILE_FOR_INCLUDES ON CACHE BOOL "Use response file")
        set(CMAKE_C_USE_RESPONSE_FILE_FOR_LIBRARIES ON CACHE BOOL "Use response file")
        set(CMAKE_CXX_USE_RESPONSE_FILE_FOR_LIBRARIES ON CACHE BOOL "Use response file")
        set(CMAKE_CXX_USE_RESPONSE_FILE_FOR_OBJECTS ON CACHE BOOL "Use response file")
        set(CMAKE_CXX_RESPONSE_FILE_LINK_FLAG "@" CACHE STRING "Response file link flag")
        set(CMAKE_C_RESPONSE_FILE_LINK_FLAG "@" CACHE STRING "Response file link flag")
    endif()
endfunction()